#
# `read_data()`: utility function to import (x, y) data generated by
# `plotdigitizer.sh`.
#
read_data <- function(file) {
  read_csv(file, skip = 6L, col_select = 1:2, col_names = c("x", "y"), col_types = "dd")
}
